### ISSUE TITLE
requirements-colab pytorch-lightning version should be bumped

### ISSUE THREAD

**Issue by turian** [GuitarML/PedalNetRT#27]
This is what I get with current ptl 1.1.0 from requirements-colab.txt in the Colab notebook:

```
!python3 train.py data/ts9_test1_in_FP32.wav data/ts9_test1_out_FP32.wav
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 60, in <module>
    from pytorch_lightning import metrics
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.metric import Metric
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/metric.py", line 23, in <module>
    from pytorch_lightning.metrics.utils import _flatten, dim_zero_cat, dim_zero_mean, dim_zero_sum
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 24, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 25, in <module>
    from torchtext.data import Batch
ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)
```

However, if I just:
```
pip3 install --upgrade pytorch-lightning
```
the colab runs just fine.

**Comment by GuitarML** [comment]
Good catch, I got the same error and the latest version fixes it. I'll update the requirements doc to point to the 1.2.10, thanks for bringing this up and finding the solution!

**Comment by GuitarML** [comment]
Fixed in commit  https://github.com/GuitarML/PedalNetRT/commit/a1281511176a0fede524a3fe26dd0e914913cbd7
