### ISSUE TITLE
Python error when training

### ISSUE THREAD

**Issue by jackcolt** [GuitarML/PedalNetRT#29]
Really cool stuff here.  Thank you.  

When running the train.py, I get the following cryptic python error.  Any thoughts?  I can train the LTSM models no problem using the source straight out of the repo.

Traceback (most recent call last):
  File "train.py", line 56, in <module>
    main(args)
  File "train.py", line 21, in main
    model = PedalNet(vars(args))
  File "/home/jack/PedalNetRT/model.py", line 118, in __init__
    self.hparams = hparams
  File "/home/jack/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by mishushakov** [comment]
hey, what command line argument are you using with `train.py`?

**Comment by GuitarML** [comment]
@jackcolt Haven't been able to reproduce what you're seeing, are you still getting this or has it been resolved?

**Comment by dobell-christopher** [comment]
Change line 118 in module.py from
self.hparams = hparams
to:
self.hparams.update(hparams)

You must have a newer version of pytorch as self.hparams = hparams no longer works in the new version

**Comment by JamesJieranShen** [comment]
> 

For proper model restoration, it also seems necessary to call `self.save_hyperparameters()` afterwards.
