### ISSUE TITLE
Issue getting predict to run

### ISSUE THREAD

**Issue by JordanDavis-1** [GuitarML/PedalNetRT#33]
I got a collab set up and trying to get the example running on my own .wav. Unfortunately I am receiving this error:

`Traceback (most recent call last):
  File "predict.py", line 58, in <module>
    predict(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "predict.py", line 17, in predict
    model = PedalNet.load_from_checkpoint(args.model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 1501, in load_from_checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.parsing'`

**Comment by mishushakov** [comment]
what's your PyTorch and PyTorch Lightning version?

try:

```py
import torch
print(torch.__version__)
```

```py
import pytorch_lightning as pl
print(pl.__version__)
```

**Comment by JordanDavis-1** [comment]
torch is 1.4.0
lightning is 0.7.3

**Comment by mishushakov** [comment]
are you using the notebook provided?
https://github.com/GuitarML/PedalNetRT/blob/master/notebooks/colab_GPU_playground.ipynb

in the requirements we list `pytorch_lightning==1.2.10`, try to install them into colab

```
!pip install pytorch_lightning==1.2.10
```

or

```
!pip install -r requirements-colab.txt
```
